- name: Install Chrony
  ansible.builtin.apt:
    name: chrony

- name: Install Chrony config
  ansible.builtin.copy:
    content: |
      allow 10.0.42.0/16
      local stratum 8
      makestep 1 -1
    dest: /etc/chrony/conf.d/local.conf
    mode: '644'
  notify:
    - Restart
