pis:
  hosts:
    10.0.42.[1:6]:
      ansible_user: gcndemo
brokers:
  hosts:
    10.0.42.[1:3]:
      pitft_rotate: 2
      tui: broker
    "10.0.42.1":
      broker_id: 1
    "10.0.42.2":
      broker_id: 2
    "10.0.42.3":
      broker_id: 3
clients:
  hosts:
    10.0.42.[4:6]:
      pitft_rotate: 0
      tui: client
    "10.0.42.4":
      kafka_topic: red
    "10.0.42.5":
      kafka_topic: green
    "10.0.42.6":
      kafka_topic: blue
ntpd:
  hosts:
    "10.0.42.1":
ntp:
  hosts:
    10.0.42.[2:6]:
      ntp_host: '10.0.42.1'
