- name: Configure all hosts
  become: true
  hosts: all
  roles:
    - common
    - tui

- name: Configure brokers
  become: true
  hosts: brokers
  roles:
    - broker

- name: Configure NTP server
  become: true
  hosts: ntpd
  roles:
    - ntpd

- name: Configure NTP clients
  become: true
  hosts: ntp
  roles:
    - ntp
